### ISSUE TITLE
doc refered to basler

### ISSUE THREAD

**Issue by PhilLAL** [esrf-bliss/Lima-camera-marccd#6]
Hi, 
I noticed several typos :
- some parts refer to basler (including title and abstract) in https://lima1.readthedocs.io/en/latest/camera/marccd/doc/tango.html?highlight=Basler#basler-tango-device
- image_path refers to inter packet delay in https://lima1.readthedocs.io/en/latest/camera/marccd/doc/tango.html?highlight=image_path#properties
Regards

**Comment by laurent-claustre** [comment]
Thanks Philippe, this is fixed now, doc is up to date, and I made new package to fix default value for the tango device properties
